# Generated by Django 3.2.3 on 2021-06-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('picture', models.ImageField(upload_to='book/%Y/%m/%d/', verbose_name='Фото обложки')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('active', models.BooleanField(verbose_name='Доступна для заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
        ),
    ]
