# Generated by Django 3.2.3 on 2021-06-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210617_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(help_text='Вначале имя, потом фамилия', max_length=200, verbose_name='Название книги'),
        ),
    ]
