# Generated by Django 3.2.3 on 2021-06-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0006_author_picture'),
        ('books', '0005_auto_20210619_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='authors', to='spravochniki.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название книги'),
        ),
    ]
