# Generated by Django 3.2.3 on 2021-06-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_publication',
            field=models.IntegerField(default=2012, verbose_name='Год издания'),
            preserve_default=False,
        ),
    ]
