# Generated by Django 3.2.3 on 2021-06-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_year_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=1, verbose_name='Количество страниц'),
            preserve_default=False,
        ),
    ]
