# Generated by Django 3.2.3 on 2021-06-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='binding',
            field=models.CharField(default='soft', max_length=100, verbose_name='Переплет'),
            preserve_default=False,
        ),
    ]
