# Generated by Django 3.2.3 on 2021-06-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format_book',
            field=models.CharField(default='soft', max_length=100, verbose_name='Формат книги'),
            preserve_default=False,
        ),
    ]
