# Generated by Django 3.2.3 on 2021-06-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_limit',
            field=models.CharField(default='from 5+', max_length=50, verbose_name='Возрастные ограничения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, verbose_name='ISBN'),
        ),
    ]
