# Generated by Django 3.2.3 on 2021-06-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_publishing_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount_available_books',
            field=models.IntegerField(default=1, verbose_name='Количество книг в наличии'),
            preserve_default=False,
        ),
    ]
