# Generated by Django 3.2.3 on 2021-06-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_book_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=1, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
