# Generated by Django 3.2.3 on 2021-05-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0003_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publishing_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Издательство')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
