# Generated by Django 3.2.3 on 2021-06-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0005_auto_20210604_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(default='evet', upload_to='author/%Y/%m/%d/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
